print("##############################")
print("#                            #")
print("#  Muhammad Adika Rizqullah  #")
print("#       2210817310004        #")
print("#                            #")
print("##############################")